### ISSUE TITLE
Traceback Error appleSingleTool is not defined

### ISSUE THREAD

**Issue by seansgm** [tburgin/AbsoluteManageExport#15]
Only just updated from 1d504c1 (15th April) and now I'm getting traceback errors; see below.

Script assumes location of LANrev Admin app. My install of LANrev Admin app happens to be a different path.  Editing the python script to change the defined path for appleSingleTool to the apps location seems to fix the issue.

Should we expect to install Absolute as defined in the script or should there be a way to allow alternative paths?  Created a symlink for the moment.

```
AbsoluteManageExport: [+] Creating [/Volumes/DATA/autopkg/Cache/local.Future.Absolute.CoRD/CoRD-0.5.7.amsdpackages/Payloads]
Traceback (most recent call last):
  File "/usr/local/bin/autopkg", line 1469, in <module>
    sys.exit(main(sys.argv))
  File "/usr/local/bin/autopkg", line 1463, in main
    exit(subcommands[verb]['function'](argv))
  File "/usr/local/bin/autopkg", line 1287, in run_recipes
    autopackager.process(recipe)
  File "/Library/AutoPkg/autopkglib/__init__.py", line 466, in process
    self.env = processor.process()
  File "/Library/AutoPkg/autopkglib/__init__.py", line 295, in process
    self.main()
  File "/Volumes/DATA/autopkg/RecipeRepos/com.github.tburgin.AbsoluteManageExport/AbsoluteManageExport.py", line 455, in main
    self.export_amsdpackages(source_payload, dest_payload, sdpackages_ampkgprops, sd_name_prefix, payload_name_prefix, sec_to_add, import_pkg, installation_condition_name, installation_condition_version_string)
  File "/Volumes/DATA/autopkg/RecipeRepos/com.github.tburgin.AbsoluteManageExport/AbsoluteManageExport.py", line 366, in export_amsdpackages
    self.output("[!] Please make sure [%s] exists" % appleSingleTool)
NameError: global name 'appleSingleTool' is not defined
```

**Comment by patgmac** [comment]
I think previous versions were using the appleSingleTool from the agent, which meant the admin workstation had to have an agent to use AbsoluteManageExport.py. Having the admin console is a safer assumption, but searching the HD for its' location could be expensive. I don't see its location specified in com.poleposition-sw.lanrev_admin.plist so not sure if there's a better way to locate it. Any ideas on how it might be located?

**Comment by tburgin** [comment]
We could add an optional entry to the `input_variables` to support a custom `LANrev Admin app` path.

Alternatively we could just search `/Applications` and `~/Applications`

Pull requests are welcome :)

**Comment by jbaker10** [comment]
Commit https://github.com/tburgin/AbsoluteManageExport/commit/cf35c685b6f3c76cf0e9aa2a62cb936de0a4418e should fix the error you are seeing. It will not fix the issue/check of whether the AppleSingleTool actually exists in the right location or not, but the recipe also won't crash, but rather will now exit with a log properly.

Please test and let us know your results.

**Comment by seansgm** [comment]
Jeremy,

Yeah, instead of seeing:

global name 'appleSingleTool' is not defined

Failed.


I'm now seeing:


AbsoluteManageExport: [!] Please make sure [/Applications/LANrev
Admin.app/Contents/MacOS/AppleSingleTool] exists

[Errno 2] No such file or directory

Failed.


Thanks.  Tom's already probably made the best suggestions.  I'd have
thought that the former would be better as the search is still making an
assumption.


Might be worth just updating the README to inform anyone that this is a
requirement.


Sean
